#! /bin/ksh

tempfile=$(mktemp)
find src -type d | \
	awk  'BEGIN { FS="/" }  { print $2 }' | \
  	awk 'NF>0' > "$tempfile"

cmake_file='cmake_loaddirlist'

printf "%s\n" 'set( cm_src "src" )' > "$cmake_file"
cm_dirs='\t${cm_src}'"\n"
cm_source='\t${cm_src}\\*.c'"\n"

while read -r line
do

	cm_dir='cm_'"$line"
	cm_dirs="$cm_dirs""\t"'${'$cm_dir'}'"\n"
	cm_source="$cm_source""\t"'${'$cm_dir'}\\*.c'"\n"
	setline='set( '"$cm_dir"' "src/'"$line"'" )'
	printf "\t%s\n" "$setline" >> "$cmake_file"

done < "$tempfile"

printf "\n%s\n" 'include_directories(' >> "$cmake_file"
printf "$cm_dirs" >> "$cmake_file"
printf "\t%s\n" ')' >> "$cmake_file"

printf "\n%s\n" 'file( GLOB cm_allsource' >> "$cmake_file"
printf "$cm_source" >> "$cmake_file"
printf "\t%s\n" ')' >> "$cmake_file"

printf "\n"'add_library( ignotalib SHARED ${cm_allsource}'"\n" \
       	>> "$cmake_file"
