#! /bin/ksh

tempfile=$(mktemp)
tempfile2=$(mktemp)
find src -type d -maxdepth 1 | \
	awk  'BEGIN { FS="/" }  { print $2 }' | \
  	awk 'NF>0' > "$tempfile"


cmake_file='cmake_loadinclude'

printf "%s\n" 'set( cm_src "src" )' > "$cmake_file"
cm_dirs='\t${cm_src}'"\n"
cm_source='\t"${cm_src}/*.c"'"\n"

ignotah='src/ignota.h'
ignotac='src/ignota.c'

rm -f "$ignotah"
rm -f "$ignotac"

find src -type f -maxdepth 1 -iname '*.H' > "$tempfile2"
cat "$tempfile2"


cat IGNOTA_LICENSE > "$ignotah"
cat IGNOTA_LICENSE > "$ignotac"

printf "\n" >> "$ignotah"
printf "\n" >> "$ignotac"

printf "#include \"ignota.h\"\n" >> "$ignotac"

printf "#ifndef IGNOTA_H\n" >> "$ignotah"
printf "#define IGNOTA_H\n\n" >> "$ignotah"

while IFS= read -r line
do
	echo "$line"

	cm_dir='cm_'"$line"
	cm_dirs="$cm_dirs""\t"'${'$cm_dir'}'"\n"
	cm_source="$cm_source""\t"'"${'$cm_dir'}/*.c"'"\n"
	setline='set( '"$cm_dir"' "src/'"$line"'" )'
	printf "%s\n" "$setline" >> "$cmake_file"

	#source header maker

	./gen_summary_header 'src/'"$line"
	printf "#include \"""$line""/""$line"".h\"\n" >> "$ignotah"

done < "$tempfile"

printf "\n" >> "$ignotah"

while IFS= read -r line
do

	printf "#include \"""${line#*/}""\"\n" >> "$ignotah"

done < "$tempfile2"

#finish inside src sources

printf "\n#endif \n" >> "$ignotah"

printf "\n%s\n" 'include_directories(' >> "$cmake_file"
printf "$cm_dirs" >> "$cmake_file"
printf "\t%s\n" ')' >> "$cmake_file"

printf "\n%s\n" 'file( GLOB cm_allsource' >> "$cmake_file"
printf "$cm_source" >> "$cmake_file"
printf "\t%s\n" ')' >> "$cmake_file"

printf "\n"'add_library( ignota SHARED ${cm_allsource} )'"\n" \
       	>> "$cmake_file"

printf "\n"'install( TARGETS ignota DESTINATION lib )'"\n" \
       	>> "$cmake_file"


rm -f "$tempfile"
rm -f "$tempfile2"
