# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/piotr/dokumenty/00progr/moje_programy/ignota

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/piotr/dokumenty/00progr/moje_programy/ignota

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/piotr/dokumenty/00progr/moje_programy/ignota/CMakeFiles /home/piotr/dokumenty/00progr/moje_programy/ignota//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/piotr/dokumenty/00progr/moje_programy/ignota/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ignotalib

# Build rule for target.
ignotalib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ignotalib
.PHONY : ignotalib

# fast build rule for target.
ignotalib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/build
.PHONY : ignotalib/fast

src/ig_compress/ig_compress.o: src/ig_compress/ig_compress.c.o

.PHONY : src/ig_compress/ig_compress.o

# target to build an object file
src/ig_compress/ig_compress.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_compress/ig_compress.c.o
.PHONY : src/ig_compress/ig_compress.c.o

src/ig_compress/ig_compress.i: src/ig_compress/ig_compress.c.i

.PHONY : src/ig_compress/ig_compress.i

# target to preprocess a source file
src/ig_compress/ig_compress.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_compress/ig_compress.c.i
.PHONY : src/ig_compress/ig_compress.c.i

src/ig_compress/ig_compress.s: src/ig_compress/ig_compress.c.s

.PHONY : src/ig_compress/ig_compress.s

# target to generate assembly for a file
src/ig_compress/ig_compress.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_compress/ig_compress.c.s
.PHONY : src/ig_compress/ig_compress.c.s

src/ig_compress/igc_probability.o: src/ig_compress/igc_probability.c.o

.PHONY : src/ig_compress/igc_probability.o

# target to build an object file
src/ig_compress/igc_probability.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_compress/igc_probability.c.o
.PHONY : src/ig_compress/igc_probability.c.o

src/ig_compress/igc_probability.i: src/ig_compress/igc_probability.c.i

.PHONY : src/ig_compress/igc_probability.i

# target to preprocess a source file
src/ig_compress/igc_probability.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_compress/igc_probability.c.i
.PHONY : src/ig_compress/igc_probability.c.i

src/ig_compress/igc_probability.s: src/ig_compress/igc_probability.c.s

.PHONY : src/ig_compress/igc_probability.s

# target to generate assembly for a file
src/ig_compress/igc_probability.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_compress/igc_probability.c.s
.PHONY : src/ig_compress/igc_probability.c.s

src/ig_datastructure/ig_datastructure.o: src/ig_datastructure/ig_datastructure.c.o

.PHONY : src/ig_datastructure/ig_datastructure.o

# target to build an object file
src/ig_datastructure/ig_datastructure.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_datastructure/ig_datastructure.c.o
.PHONY : src/ig_datastructure/ig_datastructure.c.o

src/ig_datastructure/ig_datastructure.i: src/ig_datastructure/ig_datastructure.c.i

.PHONY : src/ig_datastructure/ig_datastructure.i

# target to preprocess a source file
src/ig_datastructure/ig_datastructure.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_datastructure/ig_datastructure.c.i
.PHONY : src/ig_datastructure/ig_datastructure.c.i

src/ig_datastructure/ig_datastructure.s: src/ig_datastructure/ig_datastructure.c.s

.PHONY : src/ig_datastructure/ig_datastructure.s

# target to generate assembly for a file
src/ig_datastructure/ig_datastructure.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_datastructure/ig_datastructure.c.s
.PHONY : src/ig_datastructure/ig_datastructure.c.s

src/ig_datastructure/igds_strarr.o: src/ig_datastructure/igds_strarr.c.o

.PHONY : src/ig_datastructure/igds_strarr.o

# target to build an object file
src/ig_datastructure/igds_strarr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_datastructure/igds_strarr.c.o
.PHONY : src/ig_datastructure/igds_strarr.c.o

src/ig_datastructure/igds_strarr.i: src/ig_datastructure/igds_strarr.c.i

.PHONY : src/ig_datastructure/igds_strarr.i

# target to preprocess a source file
src/ig_datastructure/igds_strarr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_datastructure/igds_strarr.c.i
.PHONY : src/ig_datastructure/igds_strarr.c.i

src/ig_datastructure/igds_strarr.s: src/ig_datastructure/igds_strarr.c.s

.PHONY : src/ig_datastructure/igds_strarr.s

# target to generate assembly for a file
src/ig_datastructure/igds_strarr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_datastructure/igds_strarr.c.s
.PHONY : src/ig_datastructure/igds_strarr.c.s

src/ig_encoding/ig_encoding.o: src/ig_encoding/ig_encoding.c.o

.PHONY : src/ig_encoding/ig_encoding.o

# target to build an object file
src/ig_encoding/ig_encoding.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_encoding/ig_encoding.c.o
.PHONY : src/ig_encoding/ig_encoding.c.o

src/ig_encoding/ig_encoding.i: src/ig_encoding/ig_encoding.c.i

.PHONY : src/ig_encoding/ig_encoding.i

# target to preprocess a source file
src/ig_encoding/ig_encoding.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_encoding/ig_encoding.c.i
.PHONY : src/ig_encoding/ig_encoding.c.i

src/ig_encoding/ig_encoding.s: src/ig_encoding/ig_encoding.c.s

.PHONY : src/ig_encoding/ig_encoding.s

# target to generate assembly for a file
src/ig_encoding/ig_encoding.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_encoding/ig_encoding.c.s
.PHONY : src/ig_encoding/ig_encoding.c.s

src/ig_encoding/ige_base64.o: src/ig_encoding/ige_base64.c.o

.PHONY : src/ig_encoding/ige_base64.o

# target to build an object file
src/ig_encoding/ige_base64.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_encoding/ige_base64.c.o
.PHONY : src/ig_encoding/ige_base64.c.o

src/ig_encoding/ige_base64.i: src/ig_encoding/ige_base64.c.i

.PHONY : src/ig_encoding/ige_base64.i

# target to preprocess a source file
src/ig_encoding/ige_base64.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_encoding/ige_base64.c.i
.PHONY : src/ig_encoding/ige_base64.c.i

src/ig_encoding/ige_base64.s: src/ig_encoding/ige_base64.c.s

.PHONY : src/ig_encoding/ige_base64.s

# target to generate assembly for a file
src/ig_encoding/ige_base64.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_encoding/ige_base64.c.s
.PHONY : src/ig_encoding/ige_base64.c.s

src/ig_encoding/ige_rot13.o: src/ig_encoding/ige_rot13.c.o

.PHONY : src/ig_encoding/ige_rot13.o

# target to build an object file
src/ig_encoding/ige_rot13.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_encoding/ige_rot13.c.o
.PHONY : src/ig_encoding/ige_rot13.c.o

src/ig_encoding/ige_rot13.i: src/ig_encoding/ige_rot13.c.i

.PHONY : src/ig_encoding/ige_rot13.i

# target to preprocess a source file
src/ig_encoding/ige_rot13.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_encoding/ige_rot13.c.i
.PHONY : src/ig_encoding/ige_rot13.c.i

src/ig_encoding/ige_rot13.s: src/ig_encoding/ige_rot13.c.s

.PHONY : src/ig_encoding/ige_rot13.s

# target to generate assembly for a file
src/ig_encoding/ige_rot13.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_encoding/ige_rot13.c.s
.PHONY : src/ig_encoding/ige_rot13.c.s

src/ig_fileio/ig_fileio.o: src/ig_fileio/ig_fileio.c.o

.PHONY : src/ig_fileio/ig_fileio.o

# target to build an object file
src/ig_fileio/ig_fileio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/ig_fileio.c.o
.PHONY : src/ig_fileio/ig_fileio.c.o

src/ig_fileio/ig_fileio.i: src/ig_fileio/ig_fileio.c.i

.PHONY : src/ig_fileio/ig_fileio.i

# target to preprocess a source file
src/ig_fileio/ig_fileio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/ig_fileio.c.i
.PHONY : src/ig_fileio/ig_fileio.c.i

src/ig_fileio/ig_fileio.s: src/ig_fileio/ig_fileio.c.s

.PHONY : src/ig_fileio/ig_fileio.s

# target to generate assembly for a file
src/ig_fileio/ig_fileio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/ig_fileio.c.s
.PHONY : src/ig_fileio/ig_fileio.c.s

src/ig_fileio/igf_dir.o: src/ig_fileio/igf_dir.c.o

.PHONY : src/ig_fileio/igf_dir.o

# target to build an object file
src/ig_fileio/igf_dir.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_dir.c.o
.PHONY : src/ig_fileio/igf_dir.c.o

src/ig_fileio/igf_dir.i: src/ig_fileio/igf_dir.c.i

.PHONY : src/ig_fileio/igf_dir.i

# target to preprocess a source file
src/ig_fileio/igf_dir.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_dir.c.i
.PHONY : src/ig_fileio/igf_dir.c.i

src/ig_fileio/igf_dir.s: src/ig_fileio/igf_dir.c.s

.PHONY : src/ig_fileio/igf_dir.s

# target to generate assembly for a file
src/ig_fileio/igf_dir.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_dir.c.s
.PHONY : src/ig_fileio/igf_dir.c.s

src/ig_fileio/igf_fdoffset.o: src/ig_fileio/igf_fdoffset.c.o

.PHONY : src/ig_fileio/igf_fdoffset.o

# target to build an object file
src/ig_fileio/igf_fdoffset.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_fdoffset.c.o
.PHONY : src/ig_fileio/igf_fdoffset.c.o

src/ig_fileio/igf_fdoffset.i: src/ig_fileio/igf_fdoffset.c.i

.PHONY : src/ig_fileio/igf_fdoffset.i

# target to preprocess a source file
src/ig_fileio/igf_fdoffset.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_fdoffset.c.i
.PHONY : src/ig_fileio/igf_fdoffset.c.i

src/ig_fileio/igf_fdoffset.s: src/ig_fileio/igf_fdoffset.c.s

.PHONY : src/ig_fileio/igf_fdoffset.s

# target to generate assembly for a file
src/ig_fileio/igf_fdoffset.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_fdoffset.c.s
.PHONY : src/ig_fileio/igf_fdoffset.c.s

src/ig_fileio/igf_ivoperations.o: src/ig_fileio/igf_ivoperations.c.o

.PHONY : src/ig_fileio/igf_ivoperations.o

# target to build an object file
src/ig_fileio/igf_ivoperations.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_ivoperations.c.o
.PHONY : src/ig_fileio/igf_ivoperations.c.o

src/ig_fileio/igf_ivoperations.i: src/ig_fileio/igf_ivoperations.c.i

.PHONY : src/ig_fileio/igf_ivoperations.i

# target to preprocess a source file
src/ig_fileio/igf_ivoperations.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_ivoperations.c.i
.PHONY : src/ig_fileio/igf_ivoperations.c.i

src/ig_fileio/igf_ivoperations.s: src/ig_fileio/igf_ivoperations.c.s

.PHONY : src/ig_fileio/igf_ivoperations.s

# target to generate assembly for a file
src/ig_fileio/igf_ivoperations.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_ivoperations.c.s
.PHONY : src/ig_fileio/igf_ivoperations.c.s

src/ig_fileio/igf_openfd.o: src/ig_fileio/igf_openfd.c.o

.PHONY : src/ig_fileio/igf_openfd.o

# target to build an object file
src/ig_fileio/igf_openfd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_openfd.c.o
.PHONY : src/ig_fileio/igf_openfd.c.o

src/ig_fileio/igf_openfd.i: src/ig_fileio/igf_openfd.c.i

.PHONY : src/ig_fileio/igf_openfd.i

# target to preprocess a source file
src/ig_fileio/igf_openfd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_openfd.c.i
.PHONY : src/ig_fileio/igf_openfd.c.i

src/ig_fileio/igf_openfd.s: src/ig_fileio/igf_openfd.c.s

.PHONY : src/ig_fileio/igf_openfd.s

# target to generate assembly for a file
src/ig_fileio/igf_openfd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_openfd.c.s
.PHONY : src/ig_fileio/igf_openfd.c.s

src/ig_fileio/igf_read.o: src/ig_fileio/igf_read.c.o

.PHONY : src/ig_fileio/igf_read.o

# target to build an object file
src/ig_fileio/igf_read.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_read.c.o
.PHONY : src/ig_fileio/igf_read.c.o

src/ig_fileio/igf_read.i: src/ig_fileio/igf_read.c.i

.PHONY : src/ig_fileio/igf_read.i

# target to preprocess a source file
src/ig_fileio/igf_read.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_read.c.i
.PHONY : src/ig_fileio/igf_read.c.i

src/ig_fileio/igf_read.s: src/ig_fileio/igf_read.c.s

.PHONY : src/ig_fileio/igf_read.s

# target to generate assembly for a file
src/ig_fileio/igf_read.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_read.c.s
.PHONY : src/ig_fileio/igf_read.c.s

src/ig_fileio/igf_search.o: src/ig_fileio/igf_search.c.o

.PHONY : src/ig_fileio/igf_search.o

# target to build an object file
src/ig_fileio/igf_search.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_search.c.o
.PHONY : src/ig_fileio/igf_search.c.o

src/ig_fileio/igf_search.i: src/ig_fileio/igf_search.c.i

.PHONY : src/ig_fileio/igf_search.i

# target to preprocess a source file
src/ig_fileio/igf_search.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_search.c.i
.PHONY : src/ig_fileio/igf_search.c.i

src/ig_fileio/igf_search.s: src/ig_fileio/igf_search.c.s

.PHONY : src/ig_fileio/igf_search.s

# target to generate assembly for a file
src/ig_fileio/igf_search.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_search.c.s
.PHONY : src/ig_fileio/igf_search.c.s

src/ig_fileio/igf_write.o: src/ig_fileio/igf_write.c.o

.PHONY : src/ig_fileio/igf_write.o

# target to build an object file
src/ig_fileio/igf_write.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_write.c.o
.PHONY : src/ig_fileio/igf_write.c.o

src/ig_fileio/igf_write.i: src/ig_fileio/igf_write.c.i

.PHONY : src/ig_fileio/igf_write.i

# target to preprocess a source file
src/ig_fileio/igf_write.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_write.c.i
.PHONY : src/ig_fileio/igf_write.c.i

src/ig_fileio/igf_write.s: src/ig_fileio/igf_write.c.s

.PHONY : src/ig_fileio/igf_write.s

# target to generate assembly for a file
src/ig_fileio/igf_write.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_fileio/igf_write.c.s
.PHONY : src/ig_fileio/igf_write.c.s

src/ig_memory/ig_memory.o: src/ig_memory/ig_memory.c.o

.PHONY : src/ig_memory/ig_memory.o

# target to build an object file
src/ig_memory/ig_memory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_memory/ig_memory.c.o
.PHONY : src/ig_memory/ig_memory.c.o

src/ig_memory/ig_memory.i: src/ig_memory/ig_memory.c.i

.PHONY : src/ig_memory/ig_memory.i

# target to preprocess a source file
src/ig_memory/ig_memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_memory/ig_memory.c.i
.PHONY : src/ig_memory/ig_memory.c.i

src/ig_memory/ig_memory.s: src/ig_memory/ig_memory.c.s

.PHONY : src/ig_memory/ig_memory.s

# target to generate assembly for a file
src/ig_memory/ig_memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_memory/ig_memory.c.s
.PHONY : src/ig_memory/ig_memory.c.s

src/ig_memory/igm_loadfd.o: src/ig_memory/igm_loadfd.c.o

.PHONY : src/ig_memory/igm_loadfd.o

# target to build an object file
src/ig_memory/igm_loadfd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_memory/igm_loadfd.c.o
.PHONY : src/ig_memory/igm_loadfd.c.o

src/ig_memory/igm_loadfd.i: src/ig_memory/igm_loadfd.c.i

.PHONY : src/ig_memory/igm_loadfd.i

# target to preprocess a source file
src/ig_memory/igm_loadfd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_memory/igm_loadfd.c.i
.PHONY : src/ig_memory/igm_loadfd.c.i

src/ig_memory/igm_loadfd.s: src/ig_memory/igm_loadfd.c.s

.PHONY : src/ig_memory/igm_loadfd.s

# target to generate assembly for a file
src/ig_memory/igm_loadfd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_memory/igm_loadfd.c.s
.PHONY : src/ig_memory/igm_loadfd.c.s

src/ig_net/ig_net.o: src/ig_net/ig_net.c.o

.PHONY : src/ig_net/ig_net.o

# target to build an object file
src/ig_net/ig_net.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_net/ig_net.c.o
.PHONY : src/ig_net/ig_net.c.o

src/ig_net/ig_net.i: src/ig_net/ig_net.c.i

.PHONY : src/ig_net/ig_net.i

# target to preprocess a source file
src/ig_net/ig_net.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_net/ig_net.c.i
.PHONY : src/ig_net/ig_net.c.i

src/ig_net/ig_net.s: src/ig_net/ig_net.c.s

.PHONY : src/ig_net/ig_net.s

# target to generate assembly for a file
src/ig_net/ig_net.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_net/ig_net.c.s
.PHONY : src/ig_net/ig_net.c.s

src/ig_string/ig_string.o: src/ig_string/ig_string.c.o

.PHONY : src/ig_string/ig_string.o

# target to build an object file
src/ig_string/ig_string.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_string/ig_string.c.o
.PHONY : src/ig_string/ig_string.c.o

src/ig_string/ig_string.i: src/ig_string/ig_string.c.i

.PHONY : src/ig_string/ig_string.i

# target to preprocess a source file
src/ig_string/ig_string.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_string/ig_string.c.i
.PHONY : src/ig_string/ig_string.c.i

src/ig_string/ig_string.s: src/ig_string/ig_string.c.s

.PHONY : src/ig_string/ig_string.s

# target to generate assembly for a file
src/ig_string/ig_string.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_string/ig_string.c.s
.PHONY : src/ig_string/ig_string.c.s

src/ig_string/igs_convert.o: src/ig_string/igs_convert.c.o

.PHONY : src/ig_string/igs_convert.o

# target to build an object file
src/ig_string/igs_convert.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_string/igs_convert.c.o
.PHONY : src/ig_string/igs_convert.c.o

src/ig_string/igs_convert.i: src/ig_string/igs_convert.c.i

.PHONY : src/ig_string/igs_convert.i

# target to preprocess a source file
src/ig_string/igs_convert.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_string/igs_convert.c.i
.PHONY : src/ig_string/igs_convert.c.i

src/ig_string/igs_convert.s: src/ig_string/igs_convert.c.s

.PHONY : src/ig_string/igs_convert.s

# target to generate assembly for a file
src/ig_string/igs_convert.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ig_string/igs_convert.c.s
.PHONY : src/ig_string/igs_convert.c.s

src/ignota.o: src/ignota.c.o

.PHONY : src/ignota.o

# target to build an object file
src/ignota.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ignota.c.o
.PHONY : src/ignota.c.o

src/ignota.i: src/ignota.c.i

.PHONY : src/ignota.i

# target to preprocess a source file
src/ignota.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ignota.c.i
.PHONY : src/ignota.c.i

src/ignota.s: src/ignota.c.s

.PHONY : src/ignota.s

# target to generate assembly for a file
src/ignota.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ignotalib.dir/build.make CMakeFiles/ignotalib.dir/src/ignota.c.s
.PHONY : src/ignota.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ignotalib"
	@echo "... src/ig_compress/ig_compress.o"
	@echo "... src/ig_compress/ig_compress.i"
	@echo "... src/ig_compress/ig_compress.s"
	@echo "... src/ig_compress/igc_probability.o"
	@echo "... src/ig_compress/igc_probability.i"
	@echo "... src/ig_compress/igc_probability.s"
	@echo "... src/ig_datastructure/ig_datastructure.o"
	@echo "... src/ig_datastructure/ig_datastructure.i"
	@echo "... src/ig_datastructure/ig_datastructure.s"
	@echo "... src/ig_datastructure/igds_strarr.o"
	@echo "... src/ig_datastructure/igds_strarr.i"
	@echo "... src/ig_datastructure/igds_strarr.s"
	@echo "... src/ig_encoding/ig_encoding.o"
	@echo "... src/ig_encoding/ig_encoding.i"
	@echo "... src/ig_encoding/ig_encoding.s"
	@echo "... src/ig_encoding/ige_base64.o"
	@echo "... src/ig_encoding/ige_base64.i"
	@echo "... src/ig_encoding/ige_base64.s"
	@echo "... src/ig_encoding/ige_rot13.o"
	@echo "... src/ig_encoding/ige_rot13.i"
	@echo "... src/ig_encoding/ige_rot13.s"
	@echo "... src/ig_fileio/ig_fileio.o"
	@echo "... src/ig_fileio/ig_fileio.i"
	@echo "... src/ig_fileio/ig_fileio.s"
	@echo "... src/ig_fileio/igf_dir.o"
	@echo "... src/ig_fileio/igf_dir.i"
	@echo "... src/ig_fileio/igf_dir.s"
	@echo "... src/ig_fileio/igf_fdoffset.o"
	@echo "... src/ig_fileio/igf_fdoffset.i"
	@echo "... src/ig_fileio/igf_fdoffset.s"
	@echo "... src/ig_fileio/igf_ivoperations.o"
	@echo "... src/ig_fileio/igf_ivoperations.i"
	@echo "... src/ig_fileio/igf_ivoperations.s"
	@echo "... src/ig_fileio/igf_openfd.o"
	@echo "... src/ig_fileio/igf_openfd.i"
	@echo "... src/ig_fileio/igf_openfd.s"
	@echo "... src/ig_fileio/igf_read.o"
	@echo "... src/ig_fileio/igf_read.i"
	@echo "... src/ig_fileio/igf_read.s"
	@echo "... src/ig_fileio/igf_search.o"
	@echo "... src/ig_fileio/igf_search.i"
	@echo "... src/ig_fileio/igf_search.s"
	@echo "... src/ig_fileio/igf_write.o"
	@echo "... src/ig_fileio/igf_write.i"
	@echo "... src/ig_fileio/igf_write.s"
	@echo "... src/ig_memory/ig_memory.o"
	@echo "... src/ig_memory/ig_memory.i"
	@echo "... src/ig_memory/ig_memory.s"
	@echo "... src/ig_memory/igm_loadfd.o"
	@echo "... src/ig_memory/igm_loadfd.i"
	@echo "... src/ig_memory/igm_loadfd.s"
	@echo "... src/ig_net/ig_net.o"
	@echo "... src/ig_net/ig_net.i"
	@echo "... src/ig_net/ig_net.s"
	@echo "... src/ig_string/ig_string.o"
	@echo "... src/ig_string/ig_string.i"
	@echo "... src/ig_string/ig_string.s"
	@echo "... src/ig_string/igs_convert.o"
	@echo "... src/ig_string/igs_convert.i"
	@echo "... src/ig_string/igs_convert.s"
	@echo "... src/ignota.o"
	@echo "... src/ignota.i"
	@echo "... src/ignota.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

